################################################################################
#
#  This file is part of SplashSync Project.
#
#  Copyright (C) Splash Sync <www.splashsync.com>
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
#
#  For the full copyright and license information, please view the LICENSE
#  file that was distributed with this source code.
#
#  @author Bernard Paquier <contact@splashsync.com>
#
################################################################################

################################################################
# Set any variables we need
variables:
  COMPOSER_MEMORY_LIMIT:  -1

################################################################
# Defined Pipeline Stages
stages:
  - tests

################################################################
# Functional Tests
################################################################

.core_tests:    &core_tests
    stage:      tests
    tags:
        - Dedicated
    ################################################################################
    # Install & Configure Environnement
    before_script:
        # Install Dolibarr
        - cat $CI_PROJECT_DIR/src/Resources/gitlab-ci/install_dolibarr.sh | sh
        # Install Module
        - cat $CI_PROJECT_DIR/src/Resources/gitlab-ci/install_module.sh | bash
    ################################################################################
    # Run Test Script
    script:
        # Move to Dolibarr Root Dir
        - cd /var/www/html/htdocs/custom
        # Execute Composer
        - curl -s https://raw.githubusercontent.com/BadPixxel/Php-Sdk/main/ci/composer.sh  | sh
        # Execute Grumphp Testsuite
        - curl -s https://raw.githubusercontent.com/BadPixxel/Php-Sdk/main/ci/grumphp.sh  | sh
        # Execute PhpUnit Tests
        - php vendor/bin/phpunit
    ################################################################################
    # Run After Script
    after_script:
      - curl -s https://raw.githubusercontent.com/BadPixxel/Php-Sdk/main/ci/after.sh | sh

tests:php-7.4-v12:
  image: registry.gitlab.com/badpixxel-projects/php-sdk:php-7.4
  variables:
    DOLIBARR_VERSION:  "12.0"
  <<: *core_tests

tests:php-7.3-v12:
  image: registry.gitlab.com/badpixxel-projects/php-sdk:php-7.3
  variables:
    DOLIBARR_VERSION:  "12.0"
  <<: *core_tests

tests:php-7.2-v10:
  image: registry.gitlab.com/badpixxel-projects/php-sdk:php-7.2
  variables:
    DOLIBARR_VERSION:  "10.0"
  <<: *core_tests

tests:php-7.2-v8:
  image: registry.gitlab.com/badpixxel-projects/php-sdk:php-7.2
  variables:
    DOLIBARR_VERSION:  "8.0"
  <<: *core_tests